# Series in Pandas

In [206]:
import pandas as pd

# Creating a Pandas Series from a list
data = [1,2,3,4,5,6]
series = pd.Series(data)
print(f"Series : \n{series}")
print(f"Sliced index 3 : {series[3]}")
print(type(series))

# Create pandas series with a specified index
index = ["a","b","c","d","e","f"]
series_index = pd.Series(data, index=index)
print(f"Specified index : \n{series_index}")
print(f"Sliced d index : {series_index["d"]}")

# Creating a Pandas Series from a dictionary
data_dict = {"a":1,"b":2,"c":3,"d": 4,"e": 5,"f": 6}
series_dict = pd.Series(data_dict)
print(f"B to E slicing :\n{series_dict["b":"e"]}")


# Practice

data_list = [25,26,27,28,29,30]
new_data_list = pd.Series(data_list)
new_index = ["a","b","c","d","e","f"]

new_dict = pd.Series(data_list,index = new_index)
print(new_dict[:4])

Series :
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
Sliced index 3 : 4
<class 'pandas.core.series.Series'>
Specified index :
a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64
Sliced d index : 4
B to E slicing :
b    2
c    3
d    4
e    5
dtype: int64
a    25
b    26
c    27
d    28
dtype: int64

### Basic Information in Pandas Series__
These functions collectively help analysts summarize and understand the characteristics of the data, facilitating effective data exploration and analysis.

In [158]:
data = [1,2,3,4,5,6]
series = pd.Series(data)

# Return the first n rows
first_n_rows = series.head(3)
print(f"Print first 3 : \n{first_n_rows}")

# Return the last n rows
last_n_rows = series.tail(3)
print(f"Last 3 numbers : \n{last_n_rows}")

# Return dimensions (Rows, columns)
dimension = series.shape
print(f"Dimension  : {dimension}")

stats = series.describe()
print(stats)

uique = series.unique()
print(f"Shows unique numbers : \n{uique}")
nunique = series.nunique()
print(f"Count unique numbers : \n{nunique}")

new = series[0] = 26
print(new)
print(series)

Print first 3 :
0    1
1    2
2    3
dtype: int64
Last 3 numbers :
3    4
4    5
5    6
dtype: int64
Dimension  : (6,)
count    6.000000
mean     3.500000
std      1.870829
min      1.000000
25%      2.250000
50%      3.500000
75%      4.750000
max      6.000000
dtype: float64
Shows unique numbers :
[1 2 3 4 5 6]
Count unique numbers :
6
26
0    26
1     2
2     3
3     4
4     5
5     6
dtype: int64

### Operations and Transformations in Pandas Series__
Operations and transformations in Pandas Series are crucial for modifying, enhancing, and cleaning data effectively.

They provide flexibility to adapt data to specific analyses or visualizations, preparing it for meaningful insights and ensuring data quality.

In [107]:
# Here we can add 2 series with each other.
data = [1,2,3,4,5,6]
new_data = [10,12,13,14,15,16]
series = pd.Series(data)

# Element-wise addition
result_series = series + new_data
print(f"Add new_data + data : \n{result_series}")

# Apply function to each element.

squared_series = series.apply(lambda x:x**2)
print(f"Square of Series : \n{squared_series}")

s = pd.Series([12,13,14,15,16])
new_s = s.apply(lambda x: "Pass" if x >= 14 else "Fail")
print(f"Greater or equal to 14 : \n{new_s}")

# Map values using a dictionary
mapped_series = series.map({1: 'one', 2: 'two', 3: 'three',4:'Four',5:'Five',6:'Six'})
print(f"Mapped series with values : \n{mapped_series}")

# Sort the Series by values
sorted_series = series.sort_values()
print(f"Sorted : \n{sorted_series}")

# Check for missing values
missing_values = series.isnull()
print(missing_values)

Add new_data + data :
0    11
1    14
2    16
3    18
4    20
5    22
dtype: int64
Square of Series :
0     1
1     4
2     9
3    16
4    25
5    36
dtype: int64
Greater or equal to 14 :
0    Fail
1    Fail
2    Pass
3    Pass
4    Pass
dtype: object
Mapped series with values :
0      one
1      two
2    three
3     Four
4     Five
5      Six
dtype: object
Sorted :
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [113]:
# Check for missing values

import pandas as pd

s = pd.Series([10, None, 30, np.nan, 50])

missing_values = s.isnull()

print(s)
print(missing_values)

0    10.0
1     NaN
2    30.0
3     NaN
4    50.0
dtype: float64
0    False
1     True
2    False
3     True
4    False
dtype: bool

In [116]:
# Fill missing values with a specified value
import pandas as pd

s = pd.Series([10, None, 30, None, 50])

print("Original Series:")
print(s)

filled_series = s.fillna(5)

print("\nAfter fillna(0):")
print(filled_series)

Original Series:
0    10.0
1     NaN
2    30.0
3     NaN
4    50.0
dtype: float64

After fillna(0):
0    10.0
1     5.0
2    30.0
3     5.0
4    50.0
dtype: float64

### Querying a Series__
Selecting and filtering data based on specific conditions is an essential aspect of querying a Pandas Series.

The following examples illustrate common querying operations that can be applied to a Pandas Series:

In [157]:
data = {"a":10,"b":20,"c":30,"d":40,"e":50}

dict_series = pd.Series(data)
print(f"Dictionary : \n{dict_series}")

# Select elements greater then 30.
greater_than_30 = dict_series[dict_series > 30]
print(f"Numbers greater then 30 : \n{greater_than_30}")

# Equals to 20.
equals_to_20 = dict_series[dict_series == 20]
print(f"Numbers equal to 20 : \n{equals_to_20}")

# Select elements not equals to 40.

not_equal_40 = dict_series[dict_series != 40]
print(f"Numbers not equals to 40 : \n{not_equal_40}")

# Selected elements based on multiple conditions.

multiple_conditions = dict_series[(dict_series > 10) & (dict_series < 40)]
print(f"Numbers greater the 10 less and then 40 : \n{multiple_conditions}")

# Checks value is in list or not

check = dict_series[dict_series.isin([20,40,60])]
print(f"Check if numbers exits or not : \n{check}")

# Select elements using string methods (if applicable)
string_series = pd.Series(["Apple","Mango","Banana","Cherry","Blue Berry"])

str_find = string_series[string_series.str.startswith("B")]
print(f"Find string based on starting word : \n{str_find}")

# Query based on index labels
selected_by_index_labels = series_index.loc[['a', 'c', 'e']]
print(f"Get values with index : \n{selected_by_index_labels}")

# Query based on numeric position
selected_by_numeric_position = series_index.iloc[1:4]
print(f"Get values based on numeric position : \n{selected_by_numeric_position}")

Dictionary :
a    10
b    20
c    30
d    40
e    50
dtype: int64
Numbers greater then 30 :
d    40
e    50
dtype: int64
Numbers equal to 20 :
b    20
dtype: int64
Numbers not equals to 40 :
a    10
b    20
c    30
e    50
dtype: int64
Numbers greater the 10 less and then 40 :
b    20
c    30
dtype: int64
Check if numbers exits or not :
b    20
d    40
dtype: int64
Find string based on starting word :
2        Banana
4    Blue Berry
dtype: object
Get values with index :
a    1
c    3
e    5
dtype: int64
Get values based on numeric position :
b    2
c    3
d    4
dtype: int64

# Dataframe in Pandas

In [169]:
import pandas as pd

# Creating Dataframe from Dictionary
user_data = {
    "Name": ["Ankit","Priya","Komal"],
    "Age": [32,30,28],
    "Salary": [60000,75000,50000]
}

user_detail = pd.DataFrame(user_data)
print(user_detail)

# Creating a DataFrame from lists
data_list = [['Alice', 25, 50000], ['Bob', 30, 60000], ['Charlie', 22, 45000]]
columns = ["Name","Age","Salary"]
new_list = pd.DataFrame(data_list,columns=columns)
print(new_list)

# Creating a DataFrame from a NumPy array
import numpy as np

arr = np.array([
    ["Rahul", 30, 30000],
    ["Karan", 45, 35000],
    ["Jayesh", 50, 40000]
])
columns = ["Name","Age","Salary"]
new_arr = pd.DataFrame(arr,columns = columns)
print(new_arr)

    Name  Age  Salary
0  Ankit   32   60000
1  Priya   30   75000
2  Komal   28   50000
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   22   45000
     Name Age Salary
0   Rahul  30  30000
1   Karan  45  35000
2  Jayesh  50  40000

In [88]:
import pandas as pd

# Creating a sample DataFrame
data = {'Column_name': [5, 15, 8],
        'Column1': [10, 20, 30],
        'Column2': [100, 200, 300],
        'Another_column': [25, 35, 45]}

df = pd.DataFrame(data)
print(df)

# Accessing a single column
column_data = df['Column_name']
print("Single column:")
print(column_data)

col_1 = df["Column1"]
print(col_1)

col_2 = df["Column2"]
print(col_2)

col_3 = df["Another_column"]
print(f"Specific full column : \n{col_3}")

multiple = df[["Column1","Column2"]]
print(f"Multiple Columns : \n{multiple}")

col_data = df.at[1,"Column1"]
print(f"Specific col value : \n{col_data}")

row_data = df.loc[0]
print(f"Specific row : \n{row_data}")

col_data1 = df.iat[1,1]
print(f"Specific col valuee : \n{col_data1}")

filter_condition = df[df['Column2']>200]
print(f"Filtered greater then 200 : \n{filter_condition}")

filter = df[df["Column_name"] > 10]
print(f"Filter greater then 10 : \n{filter}")

# Conditional access
selected_data = df[df['Column_name'] > 5]['Another_column']
print("\nConditional access:")
print(f"{selected_data}")

# first 2 rows
print(f"Frst 2 rows : \n{df.head(2)}")

# last 2 rows
print(f"Last 2 rows : \n{df.tail(2)}")

# Comprehensive summary of dataframe
print(f"Information : \n{df.info()}")

print(f"Shape : \n{df.shape}")

print(f"Describe shows all the detail : \n{df.describe()}")
print(f"Mean : \n{df.mean()}")
print(f"Median : \n{df.median()}")
print(f"Variance : \n{df.var()}")
print(f"Standard Deviation : \n{df.std()}")

   Column_name  Column1  Column2  Another_column
0            5       10      100              25
1           15       20      200              35
2            8       30      300              45
Single column:
0     5
1    15
2     8
Name: Column_name, dtype: int64
0    10
1    20
2    30
Name: Column1, dtype: int64
0    100
1    200
2    300
Name: Column2, dtype: int64
Specific full column :
0    25
1    35
2    45
Name: Another_column, dtype: int64
Multiple Columns :
   Column1  Column2
0       10      100
1       20      200
2       30      300
Specific col value :
20
Specific row :
Column_name         5
Column1            10
Column2           100
Another_column     25
Name: 0, dtype: int64
Specific col valuee :
20
Filtered greater then 200 :
   Column_name  Column1  Column2  Another_column
2            8       30      300              45
Filter greater then 10 :
   Column_name  Column1  Column2  Another_column
1           15       20      200              35

Conditional access:
1    35
2    45
Name: Another_column, dtype: int64
Frst 2 rows :
   Column_name  Column1  Column2  Another_column
0            5       10      100              25
1           15       20      200              35
Last 2 rows :
   Column_name  Column1  Column2  Another_column
1           15       20      200              35
2            8       30      300              45
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Column_name     3 non-null      int64
 1   Column1         3 non-null      int64
 2   Column2         3 non-null      int64
 3   Another_column  3 non-null      int64
dtypes: int64(4)
memory usage: 228.0 bytes
Information :
None
Shape :
(3, 4)
Describe shows all the detail :
       Column_name  Column1  Column2  Another_column
count     3.000000      3.0      3.0             3.0
mean      9.333333     20.0    200.0            35.0
std       5.131601     10.0    100.0            10.0
min       5.000000     10.0    100.0            25.0
25%       6.500000     15.0    150.0            30.0
50%       8.000000     20.0    200.0            35.0
75%      11.500000     25.0    250.0            40.0
max      15.000000     30.0    300.0            45.0
Mean :
Column_name         9.333333
Column1            20.000000
Column2           200.000000
Another_column     35.000000
dtype: float64
Median :
Column_name         8.0
Column1            20.0
Column2           200.0
Another_column     35.0
dtype: float64
Variance :
Column_name          26.333333
Column1             100.000000
Column2           10000.000000
Another_column      100.000000
dtype: float64
Standard Deviation :
Column_name         5.131601
Column1            10.000000
Column2           100.000000
Another_column     10.000000
dtype: float64

In [186]:
# Accessing multiple columns
selected_columns = df[['Column1', 'Column2']]
print("\nMultiple columns:")
print(selected_columns)

selected_col = df[["Column1","Another_column"]]
print(selected_col)

Multiple columns:
   Column1  Column2
0       10      100
1       20      200
2       30      300
   Column1  Another_column
0       10              25
1       20              35
2       30              45

In [187]:
# Accessing a specific row by index
row_data = df.iloc[0]
print("\nSpecific row:")
print(row_data)

Specific row:
Column_name         5
Column1            10
Column2           100
Another_column     25
Name: 0, dtype: int64

In [192]:
# Accessing rows based on a condition
filtered_rows = df[df['Column_name'] > 10]
print("\nFiltered rows:")
print(filtered_rows)

Filtered rows:
   Column_name  Column1  Column2  Another_column
1           15       20      200              35

In [194]:
# Accessing a single cell by label
value = df.at[2, 'Column_name']
print("\nSingle cell by label:")
print(value)

Single cell by label:
8

In [195]:
# Accessing a single cell by position
value = df.iat[0, 1]  # Row 0, Column 1
print("\nSingle cell by position:")
print(value)

Single cell by position:
10

In [196]:
# Accessing data using .loc
selected_data = df.loc[0, 'Column_name']
print("\nData using .loc:")
print(selected_data)

Data using .loc:
5

In [197]:
# Conditional access
selected_data = df[df['Column_name'] > 10]['Another_column']
print("\nConditional access:")
print(selected_data)

Conditional access:
1    35
Name: Another_column, dtype: int64

### Correlation Analysis
The corr() function generates a correlation matrix, indicating how variables relate to each other.

Values closer to 1 or -1 imply a stronger correlation, while values near 0 suggest a weaker correlation.

In [94]:
import pandas as pd

# Create a sample DataFrame with numeric columns
# Each key becomes a column, and each list becomes column values
data = {
    'Numeric_column1': [5, 15, 8],
    'Numeric_column2': [10, 20, 30],
    'Numeric_column3': [100, 200, 300]
}

# Convert dictionary into DataFrame (tabular format)
df = pd.DataFrame(data)

# Compute correlation matrix
# .corr() calculates correlation between all numeric columns
# Correlation tells how strongly two columns are related
# Value range:
# +1  -> Perfect positive correlation (both increase together)
#  0  -> No correlation (no relationship)
# -1  -> Perfect negative correlation (one increases, other decreases)

correlation_matrix = df.corr()

# Example explanation of correlation in this dataset:
# Numeric_column2 and Numeric_column3:
# As column2 increases (10 → 20 → 30),
# column3 also increases (100 → 200 → 300)
# → This gives strong positive correlation (~1)

# Numeric_column1 and Numeric_column2:
# Values are not increasing in a consistent pattern together
# (5 → 15 → 8 vs 10 → 20 → 30)
# → So correlation is weaker (not close to 1)

# Numeric_column1 and Numeric_column3:
# Same reason → not perfectly aligned → weaker correlation

# Print correlation matrix
print("Correlation matrix:\n", correlation_matrix)

Correlation matrix:
                  Numeric_column1  Numeric_column2  Numeric_column3
Numeric_column1         1.000000         0.292306         0.292306
Numeric_column2         0.292306         1.000000         1.000000
Numeric_column3         0.292306         1.000000         1.000000

In [98]:
data = {"Category": ["A","B","C","D","A","B","A","C","A"]}
df = pd.DataFrame(data)
print(df)

value_c = df["Category"].value_counts()
print(value_c)

  Category
0        A
1        B
2        C
3        D
4        A
5        B
6        A
7        C
8        A
Category
A    4
B    2
C    2
D    1
Name: count, dtype: int64

In [175]:
import pandas as pd

# -------------------------------
# Step 1: Create DataFrame
# -------------------------------
data = {
    "Department": ["HR", "IT", "HR", "FINANCE", "IT", "FINANCE"],
    "Employee": ["A", "B", "C", "D", "E", "F"],
    "Salary": [45000, 50000, 30000, 40000, 60000, 30000]
}

df = pd.DataFrame(data)

# Display the DataFrame
print("Original DataFrame:\n", df)


# -------------------------------
# Step 2: Average Salary per Department
# -------------------------------
# Group by Department and calculate mean salary
dept_avg_salary = df.groupby("Department")["Salary"].mean()

# Extract specific department averages
hr_dept = dept_avg_salary["HR"]
it_dept = dept_avg_salary["IT"]
finance_dept = dept_avg_salary["FINANCE"]

print("\nDepartment-wise Average Salary:\n", dept_avg_salary)
print(f"\nAverage salary of HR department: {hr_dept}")
print(f"Average salary of IT department: {it_dept}")
print(f"Average salary of Finance department: {finance_dept}")


# -------------------------------
# Step 3: Employee Count per Department
# -------------------------------
# Count number of employees in each department
employee_counts = df.groupby("Department")["Employee"].count()

print("\nDepartment-wise Employee Counts:\n", employee_counts)

# Total employees in company
total_employee = employee_counts.sum()
print(f"\nTotal Employees: {total_employee}")

# Extract individual department counts
employee_hr = employee_counts["HR"]
employee_it = employee_counts["IT"]
employee_finance = employee_counts["FINANCE"]

print("\nDepartment-wise Separate Employee Counts:")
print(f"HR: {employee_hr}")
print(f"IT: {employee_it}")
print(f"Finance: {employee_finance}")


# -------------------------------
# Step 4: Total Salary per Department
# -------------------------------
# Sum of salaries for each department
employee_salary = df.groupby("Department")["Salary"].sum()

print("\nTotal Salaries Department-wise:\n", employee_salary)

# Total salary expense of company
total_sal = employee_salary.sum()
print(f"\nTotal Salary Expense: {total_sal}")


# -------------------------------
# Step 5: Multiple Aggregations
# -------------------------------
# Apply multiple aggregate functions on Salary
employee_salary_details = df.groupby("Department")["Salary"].agg(["mean", "min", "max"])

print("\nEmployee Salary Details (mean, min, max):\n", employee_salary_details)

Original DataFrame:
   Department Employee  Salary
0         HR        A   45000
1         IT        B   50000
2         HR        C   30000
3    FINANCE        D   40000
4         IT        E   60000
5    FINANCE        F   30000

Department-wise Average Salary:
 Department
FINANCE    35000.0
HR         37500.0
IT         55000.0
Name: Salary, dtype: float64

Average salary of HR department: 37500.0
Average salary of IT department: 55000.0
Average salary of Finance department: 35000.0

Department-wise Employee Counts:
 Department
FINANCE    2
HR         2
IT         2
Name: Employee, dtype: int64

Total Employees: 6

Department-wise Separate Employee Counts:
HR: 2
IT: 2
Finance: 2

Total Salaries Department-wise:
 Department
FINANCE     70000
HR          75000
IT         110000
Name: Salary, dtype: int64

Total Salary Expense: 255000

Employee Salary Details (mean, min, max):
                mean    min    max
Department
FINANCE     35000.0  30000  40000
HR          37500.0  30000  45000
IT          55000.0  50000  60000

In [151]:
# Group by Multiple Columns
data = {
    "Department": ["HR", "HR", "IT", "IT"],
    "Gender": ["M", "F", "M", "F"],
    "Salary": [30000, 35000, 50000, 60000]
}

df = pd.DataFrame(data)

df.groupby(["Department", "Gender"])["Salary"].mean()

Department  Gender
HR          F         35000.0
            M         30000.0
IT          F         60000.0
            M         50000.0
Name: Salary, dtype: float64

In [172]:
import pandas as pd

# --------------------------------------
# Step 1: Create DataFrame
# --------------------------------------
# Dictionary where:
# - Keys = column names
# - Values = column data
data = {
    "Department": ["HR", "IT", "HR", "FINANCE", "IT", "FINANCE"],
    "Employee": ["A", "B", "C", "D", "E", "F"],
    "Emp_id": [12, 13, 14, 15, 16, 17],
    "Salary": [45000, 50000, 30000, 40000, 60000, 30000]
}

# Convert dictionary into DataFrame (table format)
df = pd.DataFrame(data)

# --------------------------------------
# Step 2: Iterating over groups
# --------------------------------------
# groupby("Department") will:
# - Split the DataFrame into groups based on Department
# - Each group contains FULL rows (not just Department column)

# Loop will run once for each unique department (HR, IT, FINANCE)
for dept, group in df.groupby("Department"):

    # 'dept' = current group name (HR / IT / FINANCE)
    print("Department:", dept)

    # 'group' = mini DataFrame containing ALL columns
    # (Employee, Emp_id, Salary) for that department only
    # Example:
    # If dept = "HR", then group will contain only HR rows
    print(group)

    # Important Understanding:
    # - Loop is NOT running on only Department column
    # - It is running on grouped DataFrames
    # - Each 'group' contains complete rows for that department

    # Internally it works like:
    # HR → all rows where Department = HR
    # IT → all rows where Department = IT
    # FINANCE → all rows where Department = FINANCE

    # So Employee, Emp_id, Salary come automatically
    # because group contains full filtered data

Department: FINANCE
  Department Employee  Emp_id  Salary
3    FINANCE        D      15   40000
5    FINANCE        F      17   30000
Department: HR
  Department Employee  Emp_id  Salary
0         HR        A      12   45000
2         HR        C      14   30000
Department: IT
  Department Employee  Emp_id  Salary
1         IT        B      13   50000
4         IT        E      16   60000

In [173]:
# --------------------------------------
# Get specific group using groupby
# --------------------------------------

# groupby("Department") creates groups based on Department
# .get_group("HR") selects only the "HR" group

hr_data = df.groupby("Department").get_group("HR")

# 'hr_data' now contains only rows where Department = HR
# It returns a mini DataFrame with all columns (Employee, Emp_id, Salary)

print(hr_data)

# Example Output:
#   Department Employee  Emp_id  Salary
# 0         HR        A      12   45000
# 2         HR        C      14   30000

# Key Understanding:
# - groupby() splits data into groups
# - get_group("HR") picks only HR group
# - Output is a filtered DataFrame (not just one column)

  Department Employee  Emp_id  Salary
0         HR        A      12   45000
2         HR        C      14   30000

In [185]:
# merge() → SQL JOIN in Pandas


df_students = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["A", "B", "C"]
})

df_marks = pd.DataFrame({
    "ID": [1, 2, 4],
    "Marks": [80, 90, 70]
})

# Inner Join

pd.merge(df_students, df_marks, on="ID", how="inner")

# # Left Join

# pd.merge(df_students, df_marks, on="ID", how="left")

# # Right Join

# pd.merge(df_students, df_marks, on="ID", how="right")

# #Outer Joins

# pd.merge(df_students, df_marks, on="ID", how="outer")

   ID Name  Marks
0   1    A     80
1   2    B     90

In [193]:
""" concat() → Stack DataFrames

👉 Used to append or combine along axis """

df1 = pd.DataFrame({
    "A": [1, 2],
    "B": [3, 4]
})

df2 = pd.DataFrame({
    "A": [5, 6],
    "B": [7, 8]
})

# pd.concat([df1, df2]) # Row-wise (default) 

# pd.concat([df1, df2], axis=1) # Column-wise

pd.concat([df1, df2], ignore_index=True) # Reset 1

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [196]:
# apply method 

df = pd.DataFrame({
    "A": [1, 2],
    "B": [3, 4]
})

df["Sum"] = df.apply(lambda row: row["A"] + row["B"], axis=1)

In [197]:
df = pd.DataFrame({
    "Marks": [40, 60, 80]
})

df["Result"] = df["Marks"].apply(lambda x: "Pass" if x >= 50 else "Fail")

print(df)

   Marks Result
0     40   Fail
1     60   Pass
2     80   Pass

### House Prices Data sets

In [198]:
import pandas as pd

df = pd.read_csv("datasets/HousePrices.csv")
print(df.head())

                  date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955
1     2.0           0     4          5        3370            280      1921
2     1.0           0     0          4        1930              0      1966
3     1.0           0     0          4        1000           1000      1963
4     1.0           0     0          4        1140            800      1976

   yr_renovated                    street       city  statezip country
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA
1             0           709 W Blaine St    Seattle  WA 98119     USA
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA
3             0           857 170th Pl NE   Bellevue  WA 98008     USA
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [248]:
# Data Cleaning

print("Data Information : \n")
print(f"{df.info()}\n")

print(f"Data Shape : \n{df.shape}")

# Remove nulls
df.dropna(inplace=True)

# Remove invalid values
df = df[df['price'] > 0]
df = df[df['bedrooms'] > 0]
df = df[df['bathrooms'] > 0]

# Fix renovated year
df.loc[df['yr_renovated'] == 0, 'yr_renovated'] = df['yr_built']

# Convert date
df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year


# Remove outliers
df = df[df['price'] < df['price'].quantile(0.99)]

# Reset index
df.reset_index(drop=True, inplace=True)

print("Data cleaned successfully ✅")
print(f"{df.info()}\n")
df.isnull().sum()
df.describe()

Data Information :

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3798 entries, 0 to 3797
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           3798 non-null   datetime64[ns]
 1   price          3798 non-null   float64
 2   bedrooms       3798 non-null   float64
 3   bathrooms      3798 non-null   float64
 4   sqft_living    3798 non-null   int64
 5   sqft_lot       3798 non-null   int64
 6   floors         3798 non-null   float64
 7   waterfront     3798 non-null   int64
 8   view           3798 non-null   int64
 9   condition      3798 non-null   int64
 10  sqft_above     3798 non-null   int64
 11  sqft_basement  3798 non-null   int64
 12  yr_built       3798 non-null   int64
 13  yr_renovated   3798 non-null   int64
 14  city           3798 non-null   object
 15  statezip       3798 non-null   object
 16  year           3798 non-null   int32
dtypes: datetime64[ns](1), float64(4), int32(1), int64(9), object(2)
memory usage: 489.7+ KB
None

Data Shape :
(3798, 17)
Data cleaned successfully ✅
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3760 entries, 0 to 3759
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           3760 non-null   datetime64[ns]
 1   price          3760 non-null   float64
 2   bedrooms       3760 non-null   float64
 3   bathrooms      3760 non-null   float64
 4   sqft_living    3760 non-null   int64
 5   sqft_lot       3760 non-null   int64
 6   floors         3760 non-null   float64
 7   waterfront     3760 non-null   int64
 8   view           3760 non-null   int64
 9   condition      3760 non-null   int64
 10  sqft_above     3760 non-null   int64
 11  sqft_basement  3760 non-null   int64
 12  yr_built       3760 non-null   int64
 13  yr_renovated   3760 non-null   int64
 14  city           3760 non-null   object
 15  statezip       3760 non-null   object
 16  year           3760 non-null   int32
dtypes: datetime64[ns](1), float64(4), int32(1), int64(9), object(2)
memory usage: 484.8+ KB
None

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,year
count,3760,3760.000000,3760.000000,3760.000000,3760.000000,3.760000e+03,3760.000000,3760.000000,3760.000000,3760.000000,3760.000000,3760.000000,3760.000000,3760.000000,3760.0
mean,2014-06-06 23:53:52.340425472,427695.724409,3.279255,2.008045,1882.956649,1.343590e+04,1.462899,0.002128,0.126862,3.439362,1623.709574,259.247074,1970.481117,1985.190691,2014.0
min,2014-05-02 00:00:00,7800.000000,1.000000,0.750000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,1901.000000,2014.0
25%,2014-05-21 00:00:00,303875.000000,3.000000,1.500000,1370.000000,5.000000e+03,1.000000,0.000000,0.000000,3.000000,1140.000000,0.000000,1951.000000,1973.000000,2014.0
50%,2014-06-09 00:00:00,415000.000000,3.000000,2.000000,1810.000000,7.479500e+03,1.000000,0.000000,0.000000,3.000000,1450.000000,0.000000,1974.000000,1994.000000,2014.0
75%,2014-06-24 00:00:00,545000.000000,4.000000,2.500000,2310.000000,1.018225e+04,2.000000,0.000000,0.000000,4.000000,2000.000000,500.000000,1995.000000,2005.000000,2014.0
max,2014-07-10 00:00:00,751000.000000,9.000000,5.750000,5960.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,5010.000000,2110.000000,2014.000000,2014.000000,2014.0
std,NaN,153989.035285,0.865031,0.674606,693.248418,3.385690e+04,0.538508,0.046084,0.543526,0.664570,656.670807,395.799992,28.996494,26.312912,0.0

In [252]:
# Mean median ,Std etc of selected data.

cols = ["sqft_lot","yr_built","price"]

for col in cols:
    print(f"Mean : {df[col].mean()}")
    print(f"Median : {df[col].median()}")
    print(f"Standard Deviation : {df[col].std()}")

Mean : 13435.901329787233
Median : 7479.5
Standard Deviation : 33856.90194710402
Mean : 1970.4811170212765
Median : 1974.0
Standard Deviation : 28.996493991902344
Mean : 427695.7244087213
Median : 415000.0
Standard Deviation : 153989.03528535963

In [260]:
# Correlation

print(f"Sqft Lot and price Correlation :{df["sqft_lot"].corr(df["price"])}")
print(f"Year Built and price correlation : {df["yr_built"].corr(df["price"])}")

Sqft Lot and price Correlation :0.05641415591660329
Year Built and price correlation : 0.05645093951605811